### ISSUE TITLE
ClientResponseError: 400, message='Bad Request', url='https://oneapi-east.telematicsct.com/v1/global/remote/refresh-status'

### ISSUE THREAD

**Issue by Intecpsp** [widewing/ha-toyota-na#105]
This error originated from a custom integration.

Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:186
integration: Toyota (North America) (documentation, issues)
First occurred: 11:54:04 PM (5 occurrences)
Last logged: 11:56:17 PM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 186, in update_vehicles_status
    await vehicle.poll_vehicle_refresh()
  File "/config/custom_components/toyota_na/patch_seventeen_cy_plus.py", line 127, in poll_vehicle_refresh
    await self._client.send_refresh_status(self._vin)
  File "/usr/local/lib/python3.13/site-packages/toyota_na/client.py", line 105, in send_refresh_status
    return await self.send_refresh_request_17cyplus(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/toyota_na/client.py", line 125, in send_refresh_request_17cyplus
    return await self.api_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/toyota_na/client.py", line 44, in api_post
    return await self.api_request("POST", endpoint, header_params, json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toyota_na/patch_client.py", line 24, in api_request
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://oneapi-east.telematicsct.com/v1/global/remote/refresh-status'

**Comment by wheindl** [comment]
I am getting the same error.  This seems to be new with 2.5.1.  The previous version completed the Toyota login but produced no entities.  (I had previous recent success with using this integration but my Toyota Connect service expired a few weeks ago.  After the expiration, certain entities no longer worked (e.g. door status), but others did (e.g. tire pressure and geolocation).  I presume the intent of the recent changes to the integration has been to support this.)

**Comment by HMGOMEZ77** [comment]
Same issue..please fix

**Comment by widewing** [comment]
v2.5.2 should fix this issue

**Comment by bmitchell76** [comment]
Yeah!  The entities are back.

**Comment by HMGOMEZ77** [comment]
Yessss.. Thank you!
