### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by cradcore** [widewing/ha-toyota-na#25]
After following the instructions and installing this integration, I am prompted to sign-in, which completes succesfully. Afterwards though, I get no new devices/entities in HA and the following in my log:
```
2022-02-06 10:51:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota_na platform for sensor
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota_na/sensor.py", line 31, in async_setup_entry
if sensor.available:
File "/config/custom_components/toyota_na/sensor.py", line 75, in available
return "fuelLevel" in self.vehicle_odometer_detail
File "/config/custom_components/toyota_na/base_entity.py", line 47, in vehicle_odometer_detail
return self.vehicle["odometer_detail"]
KeyError: 'odometer_detail'
2022-02-06 10:51:01 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up toyota_na platform for device_tracker
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota_na/device_tracker.py", line 21, in async_setup_entry
if tracker.available:
File "/config/custom_components/toyota_na/device_tracker.py", line 47, in available
return "latitude" in self.vehicle_status
File "/config/custom_components/toyota_na/base_entity.py", line 35, in vehicle_status
return self.vehicle["status"]
KeyError: 'status'
2022-02-06 10:51:36 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota_na platform for sensor
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota_na/sensor.py", line 31, in async_setup_entry
if sensor.available:
File "/config/custom_components/toyota_na/sensor.py", line 75, in available
return "fuelLevel" in self.vehicle_odometer_detail
File "/config/custom_components/toyota_na/base_entity.py", line 47, in vehicle_odometer_detail
return self.vehicle["odometer_detail"]
KeyError: 'odometer_detail'
2022-02-06 10:51:36 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up toyota_na platform for device_tracker
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota_na/device_tracker.py", line 21, in async_setup_entry
if tracker.available:
File "/config/custom_components/toyota_na/device_tracker.py", line 47, in available
return "latitude" in self.vehicle_status
File "/config/custom_components/toyota_na/base_entity.py", line 35, in vehicle_status
return self.vehicle["status"]
KeyError: 'status'
```

Running `python -m toyota_na.app get_user_vehicle_list` returns `toyota_na.exceptions.TokenExpired`, even after deleting and re-installing the add on

**Comment by cradcore** [comment]
Update: I ran python -m `toyota_na.app authorize` and the TokenExpired error went away. The generation is 17CYPLUS

**Comment by widewing** [comment]
Hmm do you have an active subscription?

**Comment by cradcore** [comment]
@widewing I do. Currently both Safety Connect and Wi-Fi Connect are active

**Comment by widewing** [comment]
How about remote connect? I think that's what does the job. Or can you see your vehicle status via Toyota app?

**Comment by cradcore** [comment]
@widewing I don't see that in my list of subscriptions. Actually don't even see the option to purchase it either. I do see my vehicle status in the toyota app, at least some of what looks like is implemented here. I see my odometer and fuel gauge, but not things like door lock status, tire pressure, etc.

**Comment by vanstinator** [comment]
Can you try this again? We fixed several bugs and added support for additional vehicles in the [latest release](https://github.com/widewing/ha-toyota-na/issues/29)

**Comment by vanstinator** [comment]
We just pushed a release that supports the diagnostic platform in HA. Navigate to the integrations page, select the menu on the `Toyota` integration, and click `Download Diagnostics`. The dump automatically redacts all sensitive information and will provide us with a lot more detail to help diagnose what's going on here.

**Comment by cradcore** [comment]
I apologize for the late response. Unfortunately something else seems to be broken after installing the integration, which doesn't let me even get to the `Download Diagnostics` option:
```
2022-05-18 11:12:05 ERROR (MainThread) [custom_components.toyota_na] Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
  File "/config/.local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
  File "/config/.local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy_plus.py", line 77, in update
    vehicle_status = await self._client.get_vehicle_status(self._vin)
  File "/config/.local/lib/python3.9/site-packages/toyota_na/client.py", line 67, in get_vehicle_status
    return await self.get_vehicle_status_17cyplus(vin)
  File "/config/.local/lib/python3.9/site-packages/toyota_na/client.py", line 80, in get_vehicle_status_17cyplus
    return await self.api_get("v1/global/remote/status", {"VIN": vin})
  File "/config/.local/lib/python3.9/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
  File "/config/.local/lib/python3.9/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status')
```

![image](https://user-images.githubusercontent.com/21273406/169075965-0c5b27f4-1559-46fd-a480-fa31c5da3416.png)

**Comment by JmactheAttack** [comment]
Seeing the same error when trying to set this up today.

From the logs:

**Comment by dkmcgowan** [comment]
If still having issues open new issue
