### ISSUE TITLE
Error when logging into integration in homeassistant

### ISSUE THREAD

**Issue by antasp3136** [widewing/ha-toyota-na#27]
2022-02-18 07:30:58 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota_na platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toyota_na/sensor.py", line 31, in async_setup_entry
    if sensor.available:
  File "/config/custom_components/toyota_na/sensor.py", line 75, in available
    return "fuelLevel" in self.vehicle_odometer_detail
  File "/config/custom_components/toyota_na/base_entity.py", line 47, in vehicle_odometer_detail
    return self.vehicle["odometer_detail"]
KeyError: 'odometer_detail'
2022-02-18 07:30:58 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up toyota_na platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toyota_na/device_tracker.py", line 21, in async_setup_entry
    if tracker.available:
  File "/config/custom_components/toyota_na/device_tracker.py", line 47, in available
    return "latitude" in self.vehicle_status
  File "/config/custom_components/toyota_na/base_entity.py", line 35, in vehicle_status
    return self.vehicle["status"]
KeyError: 'status'

**Comment by vanstinator** [comment]
Please try the [latest release](https://github.com/widewing/ha-toyota-na/issues/29) and let us know if you're still having issues.

**Comment by antasp3136** [comment]
Still cannot get this to work.. 2022-04-07 09:47:44 WARNING (MainThread) [homeassistant.config_entries] Config entry 'mxxxxxxxx11@gmail.com' for toyota_na integration not ready yet: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status'); Retrying in background
2022-04-07 09:47:49 INFO (MainThread) [root] Response status: {'messages': [{'responseCode': 'ONE-VL-10000', 'description': 'Successfully retreived all vehicles', 'detailedDescription': 'Successfully retreived all vehicles'}]}
2022-04-07 09:47:50 INFO (MainThread) [root] Response status: {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}
2022-04-07 09:47:50 INFO (MainThread) [root] Response status: SUCCESS
2022-04-07 09:47:51 INFO (MainThread) [root] Response status: {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}
2022-04-07 09:47:51 ERROR (MainThread) [custom_components.toyota_na] Error fetching data
Traceback (most recent call last):
File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
raw_vehicles = await get_vehicles(client)
File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle.py", line 37, in get_vehicles
await vehicle.update()
File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy_plus.py", line 77, in update
vehicle_status = await self._client.get_vehicle_status(self._vin)
File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 67, in get_vehicle_status
return await self.get_vehicle_status_17cyplus(vin)
File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 80, in get_vehicle_status_17cyplus
return await self.api_get("v1/global/remote/status", {"VIN": vin})
File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 41, in api_get
return await self.api_request("GET", endpoint, header_params)
File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 31, in api_request
resp.raise_for_status()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status')
2022-04-07 09:48:02 INFO (MainThread) [root] Response status: {'messages': [{'responseCode': 'ONE-VL-10000', 'description': 'Successfully retreived all vehicles', 'detailedDescription': 'Successfully retreived all vehicles'}]}
2022-04-07 09:48:02 INFO (MainThread) [root] Response status: {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}
2022-04-07 09:48:03 INFO (MainThread) [root] Response status: SUCCESS
2022-04-07 09:48:03 INFO (MainThread) [root] Response status: {'messages': [{'responseCode': 'ONE-GLOBAL-RS-10000', 'description': 'Request Completed Successfully', 'detailedDescription': 'Request Completed Successfully'}]}

**Comment by vanstinator** [comment]
We just pushed a release that supports the diagnostic platform in HA. Navigate to the integrations page, select the menu on the `Toyota` integration, and click `Download Diagnostics`. The dump automatically redacts all sensitive information and will provide us with a lot more detail to help diagnose what's going on here.

**Comment by dkmcgowan** [comment]
If this is still happening open a new issue
