### ISSUE TITLE
Toyota Notification: "Please check the rear seat of your XXXX"

### ISSUE THREAD

**Issue by nmbgeek** [widewing/ha-toyota-na#38]
After upgrading to 2.0 the integration is somewhat working.  When locking or unlocking my doors from Home Assistant a few seconds after I receive the notification from my Toyota App related to the lock/unlock I receive the notification "Please check the rear seat of your 2018 TOYOTA CAMRY 4-DOOR XSE SEDAN".  I've never seen such a notification and am not aware of any related sensor. 
 This doesn't happen all the time but is reproducible and seems to occur when lock/unlock are pressed more than once.

All sensors seem to be working except for the "Trunk" sensor which shoes as Unavailable in Home Assistant.

System Info:
Version | core-2022.3.4
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.98

Host Operating System | Home Assistant OS 7.4
Update Channel | stable
Supervisor Version | supervisor-2022.03.3
Docker Version | 20.10.9
Disk Total | 31.3 GB
Disk Used | 8.2 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok

```
2022-03-13 11:19:46 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140395102632016] 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/legacy/remote/command')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/toyota_na/lock.py", line 93, in async_lock
    await self.toggle_lock(DOOR_LOCK)
  File "/config/custom_components/toyota_na/lock.py", line 103, in toggle_lock
    await self.vehicle.send_command(COMMAND_MAP[command])
  File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy.py", line 110, in send_command
    await self._client.remote_request(
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 154, in remote_request
    return await self.remote_request_17cy(vin, command, value)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 179, in remote_request_17cy
    return await self.api_post(
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 44, in api_post
    return await self.api_request("POST", endpoint, header_params, json=json)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/legacy/remote/command')
2022-03-13 11:19:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140395102632016] 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/legacy/remote/command')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/toyota_na/lock.py", line 93, in async_lock
    await self.toggle_lock(DOOR_LOCK)
  File "/config/custom_components/toyota_na/lock.py", line 103, in toggle_lock
    await self.vehicle.send_command(COMMAND_MAP[command])
  File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy.py", line 110, in send_command
    await self._client.remote_request(
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 154, in remote_request
    return await self.remote_request_17cy(vin, command, value)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 179, in remote_request_17cy
    return await self.api_post(
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 44, in api_post
    return await self.api_request("POST", endpoint, header_params, json=json)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/legacy/remote/command')
2022-03-13 11:23:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140395102632016] 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/legacy/remote/command')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/toyota_na/lock.py", line 93, in async_lock
    await self.toggle_lock(DOOR_LOCK)
  File "/config/custom_components/toyota_na/lock.py", line 103, in toggle_lock
    await self.vehicle.send_command(COMMAND_MAP[command])
  File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy.py", line 110, in send_command
    await self._client.remote_request(
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 154, in remote_request
    return await self.remote_request_17cy(vin, command, value)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 179, in remote_request_17cy
    return await self.api_post(
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 44, in api_post
    return await self.api_request("POST", endpoint, header_params, json=json)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/legacy/remote/command')
```

**Comment by johndbritton** [comment]
I get the same message. I had assumed, perhaps incorrectly, that this was something that changed with Toyota rather than this library.

The warning about the back seat is a child detection reminder feature. I think I read somewhere online that you can turn it off via settings on the gauge cluster but I haven't investigated further.

Please share any updates here as I'd also prefer not to get that notification.

**Comment by tonymorello** [comment]
![Screenshot_20220319-204635_Toyota.jpg](https://user-images.githubusercontent.com/7967400/159143338-3f33321f-dde0-4a55-8872-b8e3528dcb46.jpg)

You need to turn it off from account > notifications settings

**Comment by vanstinator** [comment]
I don't believe that we have any control over how the vehicle gets locked or the messages that the Toyota app sends you. All we can do is request that Toyota request your vehicle be locked.

That log is certainly interesting. Was that pulled some time after locking and unlocking? @jlmaners this looks like the gen 1 vehicle API. Have you seen any of these http 500 responses in your install?

> All sensors seem to be working except for the "Trunk" sensor which shoes as Unavailable in Home Assistant.

There's a known issue with both this and the moonroof sensor. Does your Toyota app indicate you have a Trunk sensor? In the moonroof case we're including one even if the vehicle doesn't have it.

**Comment by nmbgeek** [comment]
My moonroof sensor appears to be working just the trunk showing as unavailable.
Regarding the Rear Seat Reminder I have always had child seats and items in my back seat and have never received the notification prior to using it from Home Assistant.  I have disabled it but haven't tested as of yet.

I see some gateway timeouts in the logs for the Toyota API but those appeared to be intermittent a few days ago.  I haven't used the integration much as of yet but will look into it more as well.

![camry-sensors](https://user-images.githubusercontent.com/50661551/159351503-275fe841-3b50-461a-8aea-9b214cfb48e9.PNG)

**Comment by dkmcgowan** [comment]
This is all within the Toyota app and has nothing to do with this integration
