### ISSUE TITLE
Can't Login after auth.py change

### ISSUE THREAD

**Issue by Nooka6845** [widewing/ha-toyota-na#66]
So I went through and followed the [Issue #52 ](https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1519291342) and I am getting the error below.
I thought that it was something with my auth.py file. As someone in the Issue #52 referenced that this error was before changing the auth.py file. Within in that ticket, someone copied their auth file as a text. I went ahead and copied what they had over to my auth.py file and I get the same error.

I did try my phone number instead of e-mail address for the login. Also biometric disabled on my phone.

Thank you for you help in advanced.

```powershell
toyota_na\app.py:127: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
ERROR 2024-03-18 11:51:03,802 - {"authId": "STUFF", "callbacks": [{"type": "HiddenValueCallback", "output": [{"name": "value", "value": "60"}, {"name": "id", "value": "USER_BLOCKED_REMAIN_MINUTES"}], "input": [{"name": "IDToken1", "value": "USER_BLOCKED_REMAIN_MINUTES"}]}, {"type": "HiddenValueCallback", "output": [{"name": "value", "value": "60"}, {"name": "id", "value": "USER_BLOCKED_TIME"}], "input": [{"name": "IDToken2", "value": "USER_BLOCKED_TIME"}]}]}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Lib\site-packages\toyota_na\app.py", line 132, in <module>
    main()
  File "C:\Program Files\Python312\Lib\site-packages\toyota_na\app.py", line 90, in main
    run_async(cli.auth.login(args.username, args.password))
  File "C:\Program Files\Python312\Lib\site-packages\toyota_na\app.py", line 128, in run_async
    return loop.run_until_complete(future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\toyota_na\auth.py", line 147, in login
    authorization_code = await self.authorize(username, password)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\toyota_na\auth.py", line 73, in authorize
    raise LoginError()
toyota_na.exceptions.LoginError
```

**Comment by Nooka6845** [comment]
I have also tried a previous version to see if there was something there missed. Sadly no luck :(

**Comment by Nooka6845** [comment]
Fixed my issue, figured out I really needed to just read what the issue was. first was my login was incorrect. Then just had to slowly read all the findings from #52. Now I am up and going.
