### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by s3anyboy** [widewing/ha-toyota-na#71]
Failed setup, will retry: 400, message='Bad Request', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status')

**Comment by bmitchell76** [comment]
I'm having the same issue. Could it be because I don't have an active subscription?

**Comment by bmitchell76** [comment]
Nope, I activated the service to see and I still get the same error.

**Comment by bmitchell76** [comment]
This error originated from a custom integration.

Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:104
integration: Toyota (North America) (documentation, issues)
First occurred: 9:22:42 AM (19 occurrences)
Last logged: 9:41:10 AM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy_plus.py", line 77, in update
    vehicle_status = await self._client.get_vehicle_status(self._vin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 67, in get_vehicle_status
    return await self.get_vehicle_status_17cyplus(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 80, in get_vehicle_status_17cyplus
    return await self.api_get("v1/global/remote/status", {"VIN": vin})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status')

**Comment by mrplesh** [comment]
`This error originated from a custom integration.

Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:104
integration: Toyota (North America) (documentation, issues)
First occurred: July 1, 2024 at 9:46:37 PM (223 occurrences)
Last logged: 2:39:54 AM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
TypeError: object NoneType can't be used in 'await' expression`

Getting this error after successfully logging in and using OTP

**Comment by bmitchell76** [comment]
@mrplesh so how does one go about getting it fixed?

**Comment by mrplesh** [comment]
Hoping someone can tell me lol

**Comment by Maxxiime** [comment]
Same issue

**Comment by mgoettelman** [comment]
Same here

Log details (ERROR)
This error originated from a custom integration.
Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:104
integration: Toyota (North America) ([documentation](https://github.com/widewing/ha_toyota_na), [issues](https://github.com/widewing/ha-toyota-na/issues))
First occurred: 7:17:27 AM (9 occurrences)
Last logged: 7:19:44 AM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy_plus.py", line 77, in update
    vehicle_status = await self._client.get_vehicle_status(self._vin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 67, in get_vehicle_status
    return await self.get_vehicle_status_17cyplus(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 80, in get_vehicle_status_17cyplus
    return await self.api_get("v1/global/remote/status", {"VIN": vin})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status')

**Comment by yankees5963** [comment]
same error, im assuming toyota changed their API again

**Comment by Fgreg881** [comment]
Same issue

**Comment by bmitchell76** [comment]
@dkmcgowan, I appreciate you working on this.  I was hopeful the update would address this issue but it’s still not working for me, any ideas?

**Comment by dkmcgowan** [comment]
These API calls all still work for me so no major change to the API's as I can see.  The only time I saw bad requests was when the connect service was not subscribed.  I would need to see the request object getting created to see what is different but that's inside the library we can't openly work with anymore.

**Comment by bmitchell76** [comment]
Which subscription service is required?  Safety Connect?

**Comment by dkmcgowan** [comment]
I currently have Safety Connect, Service Connect, and Remote Connect so not positive which all ones are required

**Comment by dkmcgowan** [comment]
Some of that is actually trial, it started failing on me and I subscribed to "Go Anywhere" which includes Drive Connect and Remote Connect.  I see Safety Connect and Service Connect listed as trial but without expiration, so maybe it's just bad UI.

**Comment by bmitchell76** [comment]
The last time I tinkered with this I activated safety connect, it looks like that and all other tiers include remote connect going month-to-month.  I had an option to activate a trial for Service Connect that I just activated but still no dice.

**Comment by dkmcgowan** [comment]
maybe give it some time, the activation for me didn't work right away once it expired

**Comment by nishithdev** [comment]
I have safety connect only , is there a way to bypass checking for remote connect?

**Comment by dkmcgowan** [comment]
No, the API calls do not work without remote service subscription

**Comment by mrplesh** [comment]
I am still receiving this error. 

This error originated from a custom integration.

Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:159
integration: Toyota (North America) (documentation, issues)
First occurred: 4:05:43 PM (18 occurrences)
Last logged: 4:17:11 PM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 159, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
TypeError: object NoneType can't be used in 'await' expression
